name: Buidl and Push Docker Image

on: 
  push:
    branches:
      - main

jobs:
  build-and-push:
    run-on: ubuntu-latest
  
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER_NAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      -name: Build and push
       uses: docker/build-push-actions@v5
       with:
        context: true
        tags: adonay/test1:latest

